# Naive-Bayes Model - SPAM filter_JDY

In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv('sms_spam.csv', encoding='iso-8859-1')
df_raw

type                                               text
0      ham  Hope you are having a good week. Just checking in
1      ham                            K..give back my thanks.
2      ham        Am also doing in cbe only. But have to pay.
3     spam  complimentary 4 STAR Ibiza Holiday or £10,000...
4     spam  okmail: Dear Dave this is your final notice to...
5      ham  Aiya we discuss later lar... Pick u up at 4 is...
6      ham                             Are you this much buzy
7      ham                    Please ask mummy to call father
8     spam  Marvel Mobile Play the official Ultimate Spide...
9      ham     fyi I'm at usf now, swing by the room whenever
10     ham  Sure thing big man. i have hockey elections at...
11     ham                                  I anything lor...
12     ham  By march ending, i should be ready. But will c...
13     ham                             Hmm well, night night 
14     ham  K I'll be sure to get up before noon and see w...
15     ham             Ha ha cool cool chikku chikku:-):-DB-)
16     ham  Darren was saying dat if u meeting da ge den w...
17     ham  He dint tell anything. He is angry on me that ...
18     ham  Up to u... u wan come then come lor... But i d...
19    spam  U can WIN £100 of Music Gift Vouchers every w...
20     ham     2mro i am not coming to gym machan. Goodnight.
21     ham  ARR birthday today:) i wish him to get more os...
22     ham  Reading gud habit.. Nan bari hudgi yorge patai...
23     ham  I sent my scores to sophas and i had to do sec...
24     ham    Could you not read me, my Love ? I answered you
25     ham          So what did the bank say about the money?
26     ham  Well if I'm that desperate I'll just call arma...
27     ham                Fuuuuck I need to stop sleepin, sup
28     ham                   So how's the weather over there?
29     ham                                        Ok thanx...
...    ...                                                ...
5529   ham                         Ya:)going for restaurant..
5530   ham                           At home watching tv lor.
5531   ham  No, I decided that only people who care about ...
5532  spam  Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
5533   ham                       Ok lor thanx... u in school?
5534   ham  She said,'' do u mind if I go into the bedroom...
5535   ham                                              Ok...
5536   ham  No dice, art class 6 thru 9 :( thanks though. ...
5537   ham           Good night my dear.. Sleepwell&Take care
5538  spam  HOT LIVE FANTASIES call now 08707509020 Just 2...
5539   ham   G says you never answer your texts, confirm/deny
5540   ham       Yes but I don't care cause I know its there!
5541   ham            Dear how is chechi. Did you talk to her
5542   ham  Lmao ok I wont be needing u to do my hair anym...
5543   ham  What's up my own oga. Left my phone at home an...
5544   ham  And stop wondering wow is she ever going to st...
5545   ham                      What happened to our yo date?
5546   ham              Damn, poor zac doesn't stand a chance
5547   ham              Ya very nice. . .be ready on thursday
5548   ham  ER, ENJOYIN INDIANS AT THE MO..yeP. SaLL gOoD ...
5549   ham                    Hey! There's veggie pizza... :/
5550   ham  I have 2 sleeping bags, 1 blanket and paper an...
5551  spam  Ur balance is now £500. Ur next question is: ...
5552   ham                      Already one guy loving you:-.
5553   ham               Prepare to be pounded every night...
5554   ham  You are a great role model. You are giving so ...
5555   ham  Awesome, I remember the last time we got someb...
5556  spam  If you don't, your prize will go to another cu...
5557  spam  SMS. ac JSco: Energy is high, but u may not kn...
5558   ham                    Shall call now dear having food

[5559 rows x 2 columns]

### 숫자 제거

In [3]:
#참고 사이트: https://stackoverflow.com/questions/45600662/pandas-remove-numbers-from-start-of-string-in-series?rq=1
#정수 혹은 실수를 제거.
df_delNum = df_raw.copy()
df_delNum['text']=df_delNum['text'].str.replace('\d|\f','')
df_delNum

type                                               text
0      ham  Hope you are having a good week. Just checking in
1      ham                            K..give back my thanks.
2      ham        Am also doing in cbe only. But have to pay.
3     spam  complimentary  STAR Ibiza Holiday or £, cash ...
4     spam  okmail: Dear Dave this is your final notice to...
5      ham  Aiya we discuss later lar... Pick u up at  is it?
6      ham                             Are you this much buzy
7      ham                    Please ask mummy to call father
8     spam  Marvel Mobile Play the official Ultimate Spide...
9      ham     fyi I'm at usf now, swing by the room whenever
10     ham  Sure thing big man. i have hockey elections at...
11     ham                                  I anything lor...
12     ham  By march ending, i should be ready. But will c...
13     ham                             Hmm well, night night 
14     ham  K I'll be sure to get up before noon and see w...
15     ham             Ha ha cool cool chikku chikku:-):-DB-)
16     ham  Darren was saying dat if u meeting da ge den w...
17     ham  He dint tell anything. He is angry on me that ...
18     ham  Up to u... u wan come then come lor... But i d...
19    spam  U can WIN £ of Music Gift Vouchers every week...
20     ham      mro i am not coming to gym machan. Goodnight.
21     ham  ARR birthday today:) i wish him to get more os...
22     ham  Reading gud habit.. Nan bari hudgi yorge patai...
23     ham  I sent my scores to sophas and i had to do sec...
24     ham    Could you not read me, my Love ? I answered you
25     ham          So what did the bank say about the money?
26     ham  Well if I'm that desperate I'll just call arma...
27     ham                Fuuuuck I need to stop sleepin, sup
28     ham                   So how's the weather over there?
29     ham                                        Ok thanx...
...    ...                                                ...
5529   ham                         Ya:)going for restaurant..
5530   ham                           At home watching tv lor.
5531   ham  No, I decided that only people who care about ...
5532  spam  Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
5533   ham                       Ok lor thanx... u in school?
5534   ham  She said,'' do u mind if I go into the bedroom...
5535   ham                                              Ok...
5536   ham  No dice, art class  thru  :( thanks though. An...
5537   ham           Good night my dear.. Sleepwell&Take care
5538  spam  HOT LIVE FANTASIES call now  Just p per min NT...
5539   ham   G says you never answer your texts, confirm/deny
5540   ham       Yes but I don't care cause I know its there!
5541   ham            Dear how is chechi. Did you talk to her
5542   ham  Lmao ok I wont be needing u to do my hair anym...
5543   ham  What's up my own oga. Left my phone at home an...
5544   ham  And stop wondering wow is she ever going to st...
5545   ham                      What happened to our yo date?
5546   ham              Damn, poor zac doesn't stand a chance
5547   ham              Ya very nice. . .be ready on thursday
5548   ham  ER, ENJOYIN INDIANS AT THE MO..yeP. SaLL gOoD ...
5549   ham                    Hey! There's veggie pizza... :/
5550   ham  I have  sleeping bags,  blanket and paper and ...
5551  spam  Ur balance is now £. Ur next question is: Who...
5552   ham                      Already one guy loving you:-.
5553   ham               Prepare to be pounded every night...
5554   ham  You are a great role model. You are giving so ...
5555   ham  Awesome, I remember the last time we got someb...
5556  spam  If you don't, your prize will go to another cu...
5557  spam  SMS. ac JSco: Energy is high, but u may not kn...
5558   ham                    Shall call now dear having food

[5559 rows x 2 columns]

### text 소문자화

In [4]:
# 참고 사이트 : https://stackoverflow.com/questions/22245171/how-to-lowercase-a-python-dataframe-string-column-if-it-has-missing-values
df_lower = df_delNum.copy()
df_lower['text']=df_lower['text'].str.lower()
df_lower

type                                               text
0      ham  hope you are having a good week. just checking in
1      ham                            k..give back my thanks.
2      ham        am also doing in cbe only. but have to pay.
3     spam  complimentary  star ibiza holiday or â£, cash ...
4     spam  okmail: dear dave this is your final notice to...
5      ham  aiya we discuss later lar... pick u up at  is it?
6      ham                             are you this much buzy
7      ham                    please ask mummy to call father
8     spam  marvel mobile play the official ultimate spide...
9      ham     fyi i'm at usf now, swing by the room whenever
10     ham  sure thing big man. i have hockey elections at...
11     ham                                  i anything lor...
12     ham  by march ending, i should be ready. but will c...
13     ham                             hmm well, night night 
14     ham  k i'll be sure to get up before noon and see w...
15     ham             ha ha cool cool chikku chikku:-):-db-)
16     ham  darren was saying dat if u meeting da ge den w...
17     ham  he dint tell anything. he is angry on me that ...
18     ham  up to u... u wan come then come lor... but i d...
19    spam  u can win ⣠of music gift vouchers every week...
20     ham      mro i am not coming to gym machan. goodnight.
21     ham  arr birthday today:) i wish him to get more os...
22     ham  reading gud habit.. nan bari hudgi yorge patai...
23     ham  i sent my scores to sophas and i had to do sec...
24     ham    could you not read me, my love ? i answered you
25     ham          so what did the bank say about the money?
26     ham  well if i'm that desperate i'll just call arma...
27     ham                fuuuuck i need to stop sleepin, sup
28     ham                   so how's the weather over there?
29     ham                                        ok thanx...
...    ...                                                ...
5529   ham                         ya:)going for restaurant..
5530   ham                           at home watching tv lor.
5531   ham  no, i decided that only people who care about ...
5532  spam  sunshine quiz wkly q! win a top sony dvd playe...
5533   ham                       ok lor thanx... u in school?
5534   ham  she said,'' do u mind if i go into the bedroom...
5535   ham                                              ok...
5536   ham  no dice, art class  thru  :( thanks though. an...
5537   ham           good night my dear.. sleepwell&take care
5538  spam  hot live fantasies call now  just p per min nt...
5539   ham   g says you never answer your texts, confirm/deny
5540   ham       yes but i don't care cause i know its there!
5541   ham            dear how is chechi. did you talk to her
5542   ham  lmao ok i wont be needing u to do my hair anym...
5543   ham  what's up my own oga. left my phone at home an...
5544   ham  and stop wondering wow is she ever going to st...
5545   ham                      what happened to our yo date?
5546   ham              damn, poor zac doesn't stand a chance
5547   ham              ya very nice. . .be ready on thursday
5548   ham  er, enjoyin indians at the mo..yep. sall good ...
5549   ham                    hey! there's veggie pizza... :/
5550   ham  i have  sleeping bags,  blanket and paper and ...
5551  spam  ur balance is now â£. ur next question is: who...
5552   ham                      already one guy loving you:-.
5553   ham               prepare to be pounded every night...
5554   ham  you are a great role model. you are giving so ...
5555   ham  awesome, i remember the last time we got someb...
5556  spam  if you don't, your prize will go to another cu...
5557  spam  sms. ac jsco: energy is high, but u may not kn...
5558   ham                    shall call now dear having food

[5559 rows x 2 columns]

### 불용어 제거 방법 둘

In [5]:
# 불용어 제거 방법 1
df_delStopword_1 = df_lower.copy()
df_delStopword_1['text'] = df_delStopword_1['text'].str.replace('[\{\}\[\]\/?.,;:|\)*~`!^\-_+<>@\#$%&\\\=\(\'\"]',' ')
df_delStopword_1

type                                               text
0      ham  hope you are having a good week  just checking in
1      ham                            k  give back my thanks 
2      ham        am also doing in cbe only  but have to pay 
3     spam  complimentary  star ibiza holiday or ⣠ cash ...
4     spam  okmail  dear dave this is your final notice to...
5      ham  aiya we discuss later lar    pick u up at  is it 
6      ham                             are you this much buzy
7      ham                    please ask mummy to call father
8     spam  marvel mobile play the official ultimate spide...
9      ham     fyi i m at usf now  swing by the room whenever
10     ham  sure thing big man  i have hockey elections at...
11     ham                                  i anything lor   
12     ham  by march ending  i should be ready  but will c...
13     ham                             hmm well  night night 
14     ham  k i ll be sure to get up before noon and see w...
15     ham             ha ha cool cool chikku chikku     db  
16     ham  darren was saying dat if u meeting da ge den w...
17     ham  he dint tell anything  he is angry on me that ...
18     ham  up to u    u wan come then come lor    but i d...
19    spam  u can win ⣠of music gift vouchers every week...
20     ham      mro i am not coming to gym machan  goodnight 
21     ham  arr birthday today   i wish him to get more os...
22     ham  reading gud habit   nan bari hudgi yorge patai...
23     ham  i sent my scores to sophas and i had to do sec...
24     ham    could you not read me  my love   i answered you
25     ham          so what did the bank say about the money 
26     ham  well if i m that desperate i ll just call arma...
27     ham                fuuuuck i need to stop sleepin  sup
28     ham                   so how s the weather over there 
29     ham                                        ok thanx   
...    ...                                                ...
5529   ham                         ya  going for restaurant  
5530   ham                           at home watching tv lor 
5531   ham  no  i decided that only people who care about ...
5532  spam  sunshine quiz wkly q  win a top sony dvd playe...
5533   ham                       ok lor thanx    u in school 
5534   ham  she said    do u mind if i go into the bedroom...
5535   ham                                              ok   
5536   ham  no dice  art class  thru     thanks though  an...
5537   ham           good night my dear   sleepwell take care
5538  spam  hot live fantasies call now  just p per min nt...
5539   ham   g says you never answer your texts  confirm deny
5540   ham       yes but i don t care cause i know its there 
5541   ham            dear how is chechi  did you talk to her
5542   ham  lmao ok i wont be needing u to do my hair anym...
5543   ham  what s up my own oga  left my phone at home an...
5544   ham  and stop wondering wow is she ever going to st...
5545   ham                      what happened to our yo date 
5546   ham              damn  poor zac doesn t stand a chance
5547   ham              ya very nice     be ready on thursday
5548   ham  er  enjoyin indians at the mo  yep  sall good ...
5549   ham                    hey  there s veggie pizza      
5550   ham  i have  sleeping bags   blanket and paper and ...
5551  spam  ur balance is now ⣠ ur next question is  who...
5552   ham                      already one guy loving you   
5553   ham               prepare to be pounded every night   
5554   ham  you are a great role model  you are giving so ...
5555   ham  awesome  i remember the last time we got someb...
5556  spam  if you don t  your prize will go to another cu...
5557  spam  sms  ac jsco  energy is high  but u may not kn...
5558   ham                    shall call now dear having food

[5559 rows x 2 columns]

In [6]:
# 참고 사이트 : https://stackoverrun.com/ko/q/12983392
# 불용어 제거 방법 2 
df_delStopword_2 = df_lower.copy()
df_delStopword_2 = df_delStopword_2.replace('[^\w\s]',' ',regex=True)
df_delStopword_2

type                                               text
0      ham  hope you are having a good week  just checking in
1      ham                            k  give back my thanks 
2      ham        am also doing in cbe only  but have to pay 
3     spam  complimentary  star ibiza holiday or â   cash ...
4     spam  okmail  dear dave this is your final notice to...
5      ham  aiya we discuss later lar    pick u up at  is it 
6      ham                             are you this much buzy
7      ham                    please ask mummy to call father
8     spam  marvel mobile play the official ultimate spide...
9      ham     fyi i m at usf now  swing by the room whenever
10     ham  sure thing big man  i have hockey elections at...
11     ham                                  i anything lor   
12     ham  by march ending  i should be ready  but will c...
13     ham                             hmm well  night night 
14     ham  k i ll be sure to get up before noon and see w...
15     ham             ha ha cool cool chikku chikku     db  
16     ham  darren was saying dat if u meeting da ge den w...
17     ham  he dint tell anything  he is angry on me that ...
18     ham  up to u    u wan come then come lor    but i d...
19    spam  u can win â  of music gift vouchers every week...
20     ham      mro i am not coming to gym machan  goodnight 
21     ham  arr birthday today   i wish him to get more os...
22     ham  reading gud habit   nan bari hudgi yorge patai...
23     ham  i sent my scores to sophas and i had to do sec...
24     ham    could you not read me  my love   i answered you
25     ham          so what did the bank say about the money 
26     ham  well if i m that desperate i ll just call arma...
27     ham                fuuuuck i need to stop sleepin  sup
28     ham                   so how s the weather over there 
29     ham                                        ok thanx   
...    ...                                                ...
5529   ham                         ya  going for restaurant  
5530   ham                           at home watching tv lor 
5531   ham  no  i decided that only people who care about ...
5532  spam  sunshine quiz wkly q  win a top sony dvd playe...
5533   ham                       ok lor thanx    u in school 
5534   ham  she said    do u mind if i go into the bedroom...
5535   ham                                              ok   
5536   ham  no dice  art class  thru     thanks though  an...
5537   ham           good night my dear   sleepwell take care
5538  spam  hot live fantasies call now  just p per min nt...
5539   ham   g says you never answer your texts  confirm deny
5540   ham       yes but i don t care cause i know its there 
5541   ham            dear how is chechi  did you talk to her
5542   ham  lmao ok i wont be needing u to do my hair anym...
5543   ham  what s up my own oga  left my phone at home an...
5544   ham  and stop wondering wow is she ever going to st...
5545   ham                      what happened to our yo date 
5546   ham              damn  poor zac doesn t stand a chance
5547   ham              ya very nice     be ready on thursday
5548   ham  er  enjoyin indians at the mo  yep  sall good ...
5549   ham                    hey  there s veggie pizza      
5550   ham  i have  sleeping bags   blanket and paper and ...
5551  spam  ur balance is now â   ur next question is  who...
5552   ham                      already one guy loving you   
5553   ham               prepare to be pounded every night   
5554   ham  you are a great role model  you are giving so ...
5555   ham  awesome  i remember the last time we got someb...
5556  spam  if you don t  your prize will go to another cu...
5557  spam  sms  ac jsco  energy is high  but u may not kn...
5558   ham                    shall call now dear having food

[5559 rows x 2 columns]

### 전처리 결과 확인

In [7]:
print('[19] 전처리 전:\n', df_raw['text'][19])
print('[19] 전처리 후:\n', df_delStopword_2['text'][19])

[19] 전처리 전:
 U can WIN £100 of Music Gift Vouchers every week starting NOW Txt the word DRAW to 87066 TsCs www.ldew.com SkillGame,1Winaweek, age16.150ppermessSubscription
[19] 전처리 후:
 u can win â  of music gift vouchers every week starting now txt the word draw to  tscs www ldew com skillgame winaweek  age ppermesssubscription


In [8]:
print('[22] 전처리 전: ', df_raw['text'][22])
print('[22] 전처리 후: ', df_delStopword_2['text'][22])

[22] 전처리 전:  Reading gud habit.. Nan bari hudgi yorge pataistha ertini kano:-)
[22] 전처리 후:  reading gud habit   nan bari hudgi yorge pataistha ertini kano   


### type: 'spam',  'ham' → 0, 1

In [9]:
df = df_delStopword_2.copy()
df['type'] = df.type.map({'spam':0, 'ham':1})
print(df.dtypes)
df.head()

type     int64
text    object
dtype: object


type                                               text
0     1  hope you are having a good week  just checking in
1     1                            k  give back my thanks 
2     1        am also doing in cbe only  but have to pay 
3     0  complimentary  star ibiza holiday or â   cash ...
4     0  okmail  dear dave this is your final notice to...

In [10]:
# 스팸인 글들을 모아 보기
df[df['type']==0]

type                                               text
3        0  complimentary  star ibiza holiday or â   cash ...
4        0  okmail  dear dave this is your final notice to...
8        0  marvel mobile play the official ultimate spide...
19       0  u can win â  of music gift vouchers every week...
34       0  u have won a nokia  plus a free digital camera...
38       0  spjanuary male sale  hot gay chat now cheaper ...
43       0  urgent  your mobile number has been awarded wi...
55       0  congratulations ur awarded  of cd vouchers or ...
81       0  urgent  your mobile number has been awarded wi...
82       0   s of girls many local  u who r virgins  this ...
90       0  asked mobile if  chatlines inclu in free mins ...
99       0  urgent urgent  we have  free flights to europe...
100      0  for ur chance to win a â  wkly shopping spree ...
111      0  this is the nd time we have tried to contact u...
133      0  fancy a shag  i do interested  sextextuk com t...
149      0  dear dave this is your final notice to collect...
158      0  u have a secret admirer who is looking  make c...
163      0    congratulations   in this week s competition...
165      0  show ur colours  euro     offer  get an englan...
170      0  you have been specially selected to receive a ...
172      0   p  alfie moon s children in need song on ur m...
186      0  sunshine quiz wkly q  win a top sony dvd playe...
187      0  send a logo  ur lover    names joined by a hea...
195      0  urgent  call  from landline  your complementar...
199      0  well done  your   costa del sol holiday or â  ...
200      0  free msg we billed your mobile number by mista...
219      0  last chance  claim ur â  worth of discount vou...
229      0  jamster  to get your free wallpaper text heart...
231      0  urgent  call  from your landline  your complim...
234      0  how about getting in touch with folks waiting ...
...    ...                                                ...
5385     0  had your mobile  mths  update to the latest ca...
5388     0  private  your  account statement for  fone no ...
5406     0  urgent  your mobile number has been awarded a ...
5411     0  a â  xmas reward is waiting for you  our compu...
5417     0  recpt    you have ordered a ringtone  your ord...
5419     0  loan for any purpose â    â    homeowners   te...
5426     0  shop till u drop  is it you  either k  k  â  c...
5432     0  oh my god  i ve found your number again  i m s...
5438     0  you are a winner u have been specially selecte...
5442     0  sms auction   a brand new nokia  is up  auctio...
5470     0  six chances to win cash  from  to   pounds txt...
5474     0  your free ringtone is waiting to be collected ...
5488     0  you are being contacted by our dating service ...
5489     0  i want some  my hubby s away  i need a real ma...
5492     0  for the most sparkling shopping breaks from  p...
5493     0    â  uk break accommodationvouchers terms   co...
5496     0  urgent  call  from your landline  your complim...
5500     0  more people are dogging in your area now  call...
5508     0  you are being contacted by our dating service ...
5511     0  twinks  bears  scallies  skins and jocks are c...
5512     0  dating i have had two of these  only started a...
5513     0  cds u  congratulations ur awarded â  of cd gif...
5519     0  had your mobile mths   update for free to oran...
5521     0  get  lions england tone  reply lionm  mono or ...
5525     0  for ur chance to win a â  cash every wk txt  a...
5532     0  sunshine quiz wkly q  win a top sony dvd playe...
5538     0  hot live fantasies call now  just p per min nt...
5551     0  ur balance is now â   ur next question is  who...
5556     0  if you don t  your prize will go to another cu...
5557     0  sms  ac jsco  energy is high  but u may not kn...

[747 rows x 2 columns]

## SPAM 분류

### X, Y 설정

In [11]:
# 참고 사이트: https://wikidocs.net/24869

# CountVectorizer : 문서 집합에서 단어 토큰을 생성하고 각 단어의 수를 세어 BOW 인코딩한 벡터를 만든다.
# CountVectorizer 참고 : https://datascienceschool.net/view-notebook/3e7aadbf88ed4f0d87a76f9ddc925d69/
from sklearn.feature_extraction.text import CountVectorizer

# n-gram 관련 참고 : https://datascienceschool.net/view-notebook/a0c848e1e2d343d685e6077c35c4203b/
count_ngrams = CountVectorizer(
    ngram_range=(1,3), analyzer="word", binary="False", stop_words="english")
X = count_ngrams.fit_transform(df['text'])
print(X.toarray()) 

print(count_ngrams.get_feature_names()[:5])

import numpy as np

Y = [1 if data == True else 0 for data in df['type']]
Y = np.array(Y)
print(Y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['____', '____ joy', '____ joy father', 'aa', 'aa exhaust']
[1 1 1 ... 0 0 1]


### X, Y train / test data 나누고 베르누이 나이브 베이즈 모델 돌리면서 교차검증

In [48]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.model_selection import KFold
from sklearn import linear_model, datasets
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

##kf = KFold(Y.shape[0], n_folds=5,shuffle=True, )
# K-Folds cross-validator
kf = KFold(n_splits=5,shuffle=True, )
clf = BernoulliNB()   # 0.91
# clf = MultinomialNB()   # 0.95

##for i, (train_index, test_index) in enumerate(kf):
for train_index, test_index in kf.split(X):    
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    # ravel() : Return a flattened array.
    clf.fit(X_train, y_train.ravel())

    # accuracy_score(y_true, y_pred, normalize=True, sample_weight=None) : Accuracy classification score.
    print('accuracy:',accuracy_score(y_pred = clf.predict(X_test), y_true = y_test))

TRAIN: 4447 TEST: 1112
accuracy: 0.9019784172661871
TRAIN: 4447 TEST: 1112
accuracy: 0.908273381294964
TRAIN: 4447 TEST: 1112
accuracy: 0.908273381294964
TRAIN: 4447 TEST: 1112
accuracy: 0.9181654676258992
TRAIN: 4448 TEST: 1111
accuracy: 0.9243924392439244


In [49]:
df['predict'] = clf.predict(X)  # BernoulliNB()
df

type                                               text  predict
0        1  hope you are having a good week  just checking in        1
1        1                            k  give back my thanks         1
2        1        am also doing in cbe only  but have to pay         1
3        0  complimentary  star ibiza holiday or â   cash ...        1
4        0  okmail  dear dave this is your final notice to...        0
5        1  aiya we discuss later lar    pick u up at  is it         1
6        1                             are you this much buzy        1
7        1                    please ask mummy to call father        1
8        0  marvel mobile play the official ultimate spide...        0
9        1     fyi i m at usf now  swing by the room whenever        1
10       1  sure thing big man  i have hockey elections at...        1
11       1                                  i anything lor           1
12       1  by march ending  i should be ready  but will c...        1
13       1                             hmm well  night night         1
14       1  k i ll be sure to get up before noon and see w...        1
15       1             ha ha cool cool chikku chikku     db          1
16       1  darren was saying dat if u meeting da ge den w...        1
17       1  he dint tell anything  he is angry on me that ...        1
18       1  up to u    u wan come then come lor    but i d...        1
19       0  u can win â  of music gift vouchers every week...        0
20       1      mro i am not coming to gym machan  goodnight         1
21       1  arr birthday today   i wish him to get more os...        1
22       1  reading gud habit   nan bari hudgi yorge patai...        1
23       1  i sent my scores to sophas and i had to do sec...        1
24       1    could you not read me  my love   i answered you        1
25       1          so what did the bank say about the money         1
26       1  well if i m that desperate i ll just call arma...        1
27       1                fuuuuck i need to stop sleepin  sup        1
28       1                   so how s the weather over there         1
29       1                                        ok thanx           1
...    ...                                                ...      ...
5529     1                         ya  going for restaurant          1
5530     1                           at home watching tv lor         1
5531     1  no  i decided that only people who care about ...        1
5532     0  sunshine quiz wkly q  win a top sony dvd playe...        0
5533     1                       ok lor thanx    u in school         1
5534     1  she said    do u mind if i go into the bedroom...        1
5535     1                                              ok           1
5536     1  no dice  art class  thru     thanks though  an...        1
5537     1           good night my dear   sleepwell take care        1
5538     0  hot live fantasies call now  just p per min nt...        0
5539     1   g says you never answer your texts  confirm deny        1
5540     1       yes but i don t care cause i know its there         1
5541     1            dear how is chechi  did you talk to her        1
5542     1  lmao ok i wont be needing u to do my hair anym...        1
5543     1  what s up my own oga  left my phone at home an...        1
5544     1  and stop wondering wow is she ever going to st...        1
5545     1                      what happened to our yo date         1
5546     1              damn  poor zac doesn t stand a chance        1
5547     1              ya very nice     be ready on thursday        1
5548     1  er  enjoyin indians at the mo  yep  sall good ...        1
5549     1                    hey  there s veggie pizza              1
5550     1  i have  sleeping bags   blanket and paper and ...        1
5551     0  ur balance is now â   ur next question is  who...        1
5552     1                      already one guy loving you           1
5553     1               prepa

In [51]:
# kf.split(X) : Generate indices to split data into training and test set.
list(kf.split(X))

[(array([   0,    3,    4, ..., 5555, 5556, 5557]),
  array([   1,    2,   10, ..., 5531, 5540, 5558])),
 (array([   0,    1,    2, ..., 5554, 5557, 5558]),
  array([   7,   14,   17, ..., 5552, 5555, 5556])),
 (array([   1,    2,    3, ..., 5555, 5556, 5558]),
  array([   0,    5,    9, ..., 5551, 5554, 5557])),
 (array([   0,    1,    2, ..., 5556, 5557, 5558]),
  array([   8,   23,   26, ..., 5546, 5547, 5549])),
 (array([   0,    1,    2, ..., 5556, 5557, 5558]),
  array([   3,    4,    6, ..., 5544, 5545, 5553]))]